---
title: Year Distribution of Top 100 Video Games
author: Siyi Wang
date: '2021-11-08'
slug: year-distribution-of-top-100-video-games
categories:
  - R
tags:
  - Top 100 Video Games
  - Year
---


```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(collapse = TRUE)
```

# Year Distribution of Top 100 Video Games

The plot below shows the year distribution of top 100 video games. This is an interactive graph and you can hover your mouse on the bubble to see the details.


```{r message=F,warning=F,echo=F}
########
library(ggplot2)
library(plotly)
library(data.table)
data.file<-"../vgsales.csv"
fread(data.file)->info


plot2.data<-info[order(-Global_Sales)][1:100,.(Rank,Year,Name,Global_Sales)]
plot2.data[,rank10:=cut(Rank,breaks=c(0,seq(10,100,by=10)))]
plot2.data[,rank10.size:=1/as.integer(rank10)]
plot2.data[,Year:=as.integer(Year)]

plot2.data[,label:=paste0('<b><i>',Name,'</i></b><br>',
'<b>Rank: </b>',Rank,'<br>',
'<b>Year: </b>',Year,'<br>',
'<b>Global_Sales: </b>$',Global_Sales,'<br>'
)]



plot2<-ggplot(plot2.data,aes(x=Rank,y=Year,size=rank10.size,colour=Global_Sales,text=label))+
   geom_vline(xintercept=seq(10,100,by=10),colour='#3B3131',lty=4)+
   geom_point(shape=20)+
   theme_bw()+
   scale_x_continuous(breaks=seq(10,100,by=10))+
   scale_size_continuous(guide='none')+
   scale_colour_viridis_c(begin=0.5,option='C',direction=-1)+
   scale_y_continuous(breaks=seq(1980,2015,by=5))

ggplotly(plot2,tooltip='text',width=900)

```

