---
title: Platform of Top 100 Video Games Release
author: Siyi Wang
date: '2021-11-11'
slug: platform-of-top-100-video-games-release
categories:
  - R
tags:
  - Top 100 Video Games
  - Platform
---


```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(collapse = TRUE)
```


```{css,echo=F}
	.container-fluid{
	width:930px;
	max-width:1500px !important;
	margin-left:auto;
	margin-right:auto;
	border:1px solid #B2222200;
	border-radius:1px;
	margin-top:10px;
	margin-bottom:1px;
	font-size:100%;
	font-family:Helvetica, Tahoma, Arial, STXihei, "华文细黑", Heiti, "黑体", "Microsoft YaHei", "微软雅黑", SimSun, "宋体", sans-serif;
	}
	'
```

# Platform of Top 100 Video Games Release

These interactive plots show the platform of Top 100 video games release and the number of hot video games released on those platforms and you can hover your mouse over them for more details. 


```{r message=F,warning=F,echo=F}
########
library(ggplot2)
library(plotly)
library(data.table)
library(treemapify)
library(htmltools)
library(shinydashboard)
library(shiny)


data.file<-"../vgsales.csv"
fread(data.file)->info


plot50<-info[order(-Global_Sales)][1:100,.(Rank,Global_Sales,Platform)]
plot50.count<-plot50[,.N,Platform][order(-N)]
plot50[,Platform:=ordered(Platform,levels=rev(plot50.count$Platform))]
plot50.count[,Platform:=ordered(Platform,rev(Platform))]
names(plot50.count)[2]<-'Number of Games'

plot501<-ggplot(plot50,aes(x=Rank,y=Platform,size=Global_Sales))+
    geom_point(show.legend=F,colour=NA,fill='#FBB117',shape=21)+
    scale_x_continuous(breaks=seq(10,100,by=10))+
    theme_bw()+
	scale_size_continuous(range=c(0.5,4))+
	labs(title = 'Platform of Top 100 Video Games Release')

plot502<-ggplot(plot50.count,aes(y=Platform,x=`Number of Games`))+
   theme_bw()+
   geom_bar(stat='identity',fill='#2B65EC')+
   scale_x_continuous(expand=expansion(c(0,0.02)))+
   scale_y_discrete(position='right')+
   labs(y='', title = 'Number of Top 100 Video Games released on Each Platform')+
   geom_text(aes(label=`Number of Games`),hjust=0,nudge_x=0.6,size=3)



plot5.data<-info[order(-Global_Sales)][1:100,.(Platform,Global_Sales)]
plot5.data<-plot5.data[,.(sales=sum(Global_Sales)),by=Platform]

plot5.data[,hovertext:=paste(
paste0("<b>Platform</b>",": ",Platform),
paste0("<b>Sales</b>",": $",sales),
sep="<br>"
)
]

plot_ly(data=plot5.data,ids=~Platform,labels=~Platform,
     values=~sales,parents='World Top 100',
     type='sunburst',branchvalues = 'total',text=~hovertext,
     textinfo='text',hoverinfo='text') %>% layout(title='Sales of Top 100 Video Games by Gaming Platform')
###

fluidPage(
shiny::fluidRow(shinydashboard::box(width=8,ggplotly(plot501,width=600),height='500px'),
               shinydashboard::box(width=4,ggplotly(plot502,width=400,tooltip='x')))		   
)


 
```

